before:
  hooks:
  - go mod download
builds:
- id: declcfg
  main: ./
  binary: declcfg
  asmflags:
  - all=-trimpath={{ dir .Env.PWD }}
  gcflags:
  - all=-trimpath={{ dir .Env.PWD }}
  ldflags:
  - -s
  - -w
  - -X {{ .Env.REPO }}/internal/version.GitVersion={{.Env.GIT_VERSION}}
  - -X {{ .Env.REPO }}/internal/version.GitCommit={{.Env.GIT_COMMIT}}
  - -X {{ .Env.REPO }}/internal/version.GitCommitTime={{.Env.GIT_COMMIT_TIME}}
  - -X {{ .Env.REPO }}/internal/version.GitTreeState={{.Env.GIT_TREE_STATE}}
  targets:
  - linux_amd64

# Use most recent tag and short commit for snapshot version.
snapshot:
  name_template: "{{ .Env.GIT_VERSION }}"

# We don't use archives, so skip creating them.
archives:
  - format: binary
    name_template: "{{ .Binary }}_{{ .Os }}_{{ .Arch }}{{ if .Arm }}v{{ .Arm }}{{ end }}{{ if .Mips }}_{{ .Mips }}{{ end }}"

checksum:
  name_template: "checksums.txt"
