apiVersion: operators.coreos.com/v1alpha1
kind: ClusterServiceVersion
metadata:
  annotations:
    alm-examples: '[]'
    capabilities: Basic Install
  name: dc-inherit-channels-operator.v0.0.0
  namespace: placeholder
spec:
  apiservicedefinitions: {}
  customresourcedefinitions:
    owned:
    - description: Operator is the Schema for the operators API
      displayName: Operator
      kind: Operator
      name: operators.example.my.domain
      version: v1alpha1
  description: Example operators demonstrating how declcfg works
  displayName: DC Inherit Channels Example
  icon:
  - base64data: ""
    mediatype: ""
  install:
    spec:
      deployments: null
    strategy: ""
  installModes:
  - supported: false
    type: OwnNamespace
  - supported: false
    type: SingleNamespace
  - supported: false
    type: MultiNamespace
  - supported: true
    type: AllNamespaces
  keywords:
  - declarative config
  - replaces mode
  - example
  links:
  - name: Dc Inherit Channels Operator
    url: https://dc-inherit-channels-operator.domain
  maintainers:
  - email: joe.lanford@gmail.com
    name: Joe Lanford
  maturity: alpha
  provider:
    name: Joe Lanford
    url: https://github.com/joelanford/declcfg
  version: 0.0.0
